/**
 * Drives the demo database through a whole application and photographs it.
 *
 * Everything in `docs/` is generated by this script rather than captured by
 * hand, so the walkthrough cannot drift away from the product: when a screen
 * changes, re-run it and the pictures change with it. The applicant's own
 * journey is recorded as video too, which ffmpeg turns into `docs/demo.gif`.
 *
 *   pnpm e2e:setup     # a freshly seeded database - the script needs one
 *   pnpm build && pnpm start
 *   pnpm screenshots
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { chromium, type Browser, type Page } from "@playwright/test";

const BASE_URL = process.env.SCREENSHOT_URL ?? "http://localhost:3000";
const MAILPIT_URL = process.env.MAILPIT_URL ?? "http://localhost:8025";

const OUT = path.join(process.cwd(), "docs", "screenshots");
const VIDEO_DIR = path.join(process.cwd(), "docs", ".video");
const FIXTURE_PDF = path.join(
  process.cwd(),
  "tests",
  "e2e",
  "fixtures",
  "curriculum-vitae.pdf",
);

const PASSWORD = "Portal@123";
const ACCOUNTS = {
  admin: {
    email: process.env.SUPER_ADMIN_EMAIL ?? "admin@example.org",
    password: process.env.SUPER_ADMIN_PASSWORD ?? "SuperAdmin@123",
  },
  applicant: { email: "applicant@example.org", password: PASSWORD },
  head: { email: "head@example.org", password: PASSWORD },
  deputy: { email: "deputy@example.org", password: PASSWORD },
  compliance: { email: "compliance@example.org", password: PASSWORD },
  approver: { email: "approver@example.org", password: PASSWORD },
};

const VIEWPORT = { width: 1360, height: 900 };

let shotCount = 0;

async function shot(page: Page, name: string, fullPage = false) {
  shotCount += 1;
  const file = path.join(OUT, `${name}.png`);
  // Fonts and the canvas need a beat after navigation before they are worth
  // photographing.
  await page.waitForTimeout(400);
  await page.screenshot({ path: file, fullPage });
  console.log(`  ${String(shotCount).padStart(2, "0")} ${name}.png`);
}

/**
 * Signs in through the real form, retrying through the rate-limit window
 * rather than turning the protection off for a screenshot.
 */
async function signIn(page: Page, who: keyof typeof ACCOUNTS) {
  const { email, password } = ACCOUNTS[who];

  for (let attempt = 0; attempt < 6; attempt += 1) {
    await page.goto(`${BASE_URL}/sign-in`);
    await page.getByLabel("Email address").fill(email);
    await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Sign in" }).click();

    const landed = await page
      .waitForURL(/\/dashboard/, { timeout: 10_000 })
      .then(() => true)
      .catch(() => false);
    if (landed) return;

    await page.waitForTimeout(11_000);
  }

  throw new Error(`Could not sign in as ${email}`);
}

async function openContext(
  browser: Browser,
  who: keyof typeof ACCOUNTS,
  options: { video?: boolean } = {},
) {
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: 1,
    recordVideo: options.video ? { dir: VIDEO_DIR, size: VIEWPORT } : undefined,
  });
  const page = await context.newPage();
  await signIn(page, who);
  return { context, page };
}

/* -------------------------------------------------------------------------- */
/*  Form helpers, addressing fields by their data key                          */
/* -------------------------------------------------------------------------- */

const field = (page: Page, key: string) => page.getByTestId(`field-${key}`);
const input = (page: Page, key: string) =>
  field(page, key).locator("input, textarea").first();

async function choose(page: Page, key: string, option: string) {
  await field(page, key).getByRole("combobox").click();
  await page.getByRole("option", { name: option, exact: true }).click();
}

async function next(page: Page) {
  await page.getByTestId("wizard-next").click();
  await page.waitForTimeout(500);
}

/* -------------------------------------------------------------------------- */
/*  The applicant                                                              */
/* -------------------------------------------------------------------------- */

async function applicantJourney(browser: Browser) {
  console.log("\nThe applicant");
  const { context, page } = await openContext(browser, "applicant", {
    video: true,
  });

  await shot(page, "02-dashboard-applicant");

  await page.goto(`${BASE_URL}/application`);
  const start = page.getByTestId("start-application");
  if (!(await start.isVisible().catch(() => false))) {
    throw new Error(
      "The demo applicant already has an application. Run `pnpm e2e:setup` first.",
    );
  }
  await start.click();
  await page.getByTestId("wizard-step-0").waitFor();

  await choose(page, "request_type", "Training");
  await input(page, "effective_from").fill("2026-10-01");
  await input(page, "title").fill("Advanced incident response course");
  await input(page, "justification").fill(
    "The team has no certified responder and carries the out-of-hours rota. " +
      "One certification covers the gap the last two incidents exposed.",
  );
  await shot(page, "03-form-request");
  await next(page);

  await shot(page, "04-form-prefilled");
  await next(page);

  await input(page, "cost_direct").fill("1200");
  await input(page, "cost_indirect").fill("300");
  await page.waitForTimeout(300);
  await field(page, "needs_funding").getByRole("checkbox").click();
  await input(page, "funding_source").fill("Training budget, cost centre 4021");
  await shot(page, "05-form-computed");
  await next(page);

  await page.getByTestId("earlier_requests-add").click();
  await input(page, "earlier_requests.0.reference").fill("APP-2025-0042");
  await input(page, "earlier_requests.0.year").fill("2025");
  await choose(page, "earlier_requests.0.outcome", "Withdrawn");
  await input(page, "earlier_requests.0.remarks").fill(
    "Withdrawn on cost before the vendor quote arrived.",
  );
  await shot(page, "06-form-repeating-group");
  await next(page);

  await field(page, "supporting_document")
    .locator('input[type="file"]')
    .setInputFiles(FIXTURE_PDF);
  await field(page, "supporting_document")
    .getByTestId("file-curriculum-vitae.pdf")
    .waitFor({ timeout: 30_000 });
  await shot(page, "07-form-upload");
  await next(page);

  await field(page, "declaration").getByRole("checkbox").click();
  await next(page);

  await shot(page, "08-form-preview", true);

  await page.getByTestId("submit-application").click();
  await page.getByTestId("application-progress").waitFor({ timeout: 30_000 });
  // Let the submission toast expire, then zoom the map so the steps read.
  await page.waitForTimeout(5_000);
  await zoomCanvas(page, 2);
  await shot(page, "09-tracking");

  await context.close();
}

/* -------------------------------------------------------------------------- */
/*  The people who decide it                                                   */
/* -------------------------------------------------------------------------- */

async function openReview(page: Page) {
  await page.goto(`${BASE_URL}/reviews`);
  await page.getByRole("link", { name: "Review", exact: true }).first().click();
  await page.getByTestId("open-decision").waitFor({ timeout: 30_000 });
}

async function takeOutcome(page: Page, outcome: string) {
  await page.getByTestId(`outcome-${outcome}`).click();
  await page.getByTestId(`confirm-${outcome}`).click();
  await page.waitForURL(/\/reviews$/, { timeout: 30_000 });
}

async function departmentReview(browser: Browser) {
  console.log("\nThe department head");
  const { context, page } = await openContext(browser, "head");

  await page.goto(`${BASE_URL}/reviews`);
  await shot(page, "10-review-queue");

  await openReview(page);
  await shot(page, "11-review-reading");

  await page.getByTestId("open-decision").click();
  await page.getByTestId("nominee-Send for assessment").click();
  await page.getByRole("option", { name: "Test Deputy", exact: true }).click();
  await shot(page, "12-review-decision");

  await page.getByTestId("outcome-Send for assessment").click();
  await shot(page, "13-review-confirm");
  await page.getByTestId("confirm-Send for assessment").click();
  await page.waitForURL(/\/reviews$/, { timeout: 30_000 });

  await context.close();
}

async function assessment(browser: Browser) {
  console.log("\nThe deputy the head named");
  const { context, page } = await openContext(browser, "deputy");

  await openReview(page);
  await page.getByTestId("open-decision").click();
  await page.getByRole("radio", { name: "Recommended", exact: true }).check();
  await input(page, "remarks").fill(
    "Assessed on the head's referral. The rota case is sound and the cost is " +
      "within what the department carries each year.",
  );
  await shot(page, "14-assessment");
  await next(page);
  await takeOutcome(page, "Return to the head");

  await context.close();
}

async function departmentDecision(browser: Browser) {
  console.log("\nThe head decides");
  const { context, page } = await openContext(browser, "head");

  await openReview(page);
  await page.getByTestId("open-decision").click();
  await input(page, "remarks").fill(
    "Approved. The department can carry this within the training budget.",
  );
  await next(page);
  await takeOutcome(page, "Approve");

  await context.close();
}

async function complianceCheck(browser: Browser) {
  console.log("\nCompliance");
  const { context, page } = await openContext(browser, "compliance");

  await openReview(page);
  await page.getByTestId("open-decision").click();
  await page
    .getByRole("radio", { name: "Yes, with the conditions below" })
    .check();
  await input(page, "conditions").fill(
    "Booking must go through the central travel desk.",
  );
  await input(page, "remarks").fill("Within policy on every other count.");
  await shot(page, "15-compliance-conditional");
  await next(page);
  await takeOutcome(page, "Forward for approval");

  await context.close();
}

async function finalApproval(browser: Browser) {
  console.log("\nThe approver");
  const { context, page } = await openContext(browser, "approver");

  await openReview(page);
  await shot(page, "16-every-earlier-review", true);

  await page.getByTestId("open-decision").click();
  await input(page, "remarks").fill(
    "Approved. Cost and case are both reasonable.",
  );
  await next(page);
  await takeOutcome(page, "Approve");

  await context.close();
}

async function reviewerHistory(browser: Browser) {
  console.log("\nWhat a reviewer keeps");
  const { context, page } = await openContext(browser, "head");

  await page.goto(`${BASE_URL}/dashboard`);
  await shot(page, "17-dashboard-reviewer", true);

  await page.goto(`${BASE_URL}/reviews/history`);
  await shot(page, "18-review-history");

  await context.close();
}

/**
 * React Flow zooms about the centre of the viewport, so this leaves the first
 * steps of the flow legible and in frame.
 */
async function zoomCanvas(page: Page, steps: number) {
  for (let i = 0; i < steps; i += 1) {
    await page.locator(".react-flow__controls-zoomin").click();
    await page.waitForTimeout(250);
  }
  await page.waitForTimeout(500);
}

/* -------------------------------------------------------------------------- */
/*  The administrator                                                          */
/* -------------------------------------------------------------------------- */

async function administration(browser: Browser) {
  console.log("\nAdministration");
  const { context, page } = await openContext(browser, "admin");

  await page.goto(`${BASE_URL}/applications`);
  await page.getByRole("link", { name: "View", exact: true }).first().click();
  await page.getByRole("tab", { name: "History" }).click();
  await shot(page, "19-timeline");

  await page.goto(`${BASE_URL}/admin/workflow`);
  await page.getByTestId("node-start").waitFor({ timeout: 30_000 });
  await page.waitForTimeout(1500);
  // Fit-view spreads two dozen nodes across the canvas, which photographs as
  // confetti. Zoom in on the first half of the flow instead.
  await zoomCanvas(page, 3);
  await shot(page, "20-workflow-builder");

  await page.getByTestId("node-stage-Deputy Assessment").click();
  await page.getByTestId("node-label").blur();
  await shot(page, "21-node-inspector");

  await page.getByTestId("edit-form").click();
  await page.getByTestId("form-builder-dialog").waitFor();
  await shot(page, "22-form-builder");

  // The inspector is a sheet and its overlay swallows clicks on the canvas, so
  // reload rather than trying to dismiss two layers.
  await page.goto(`${BASE_URL}/admin/workflow`);
  await page.getByTestId("node-start").waitFor({ timeout: 30_000 });
  await page.getByTestId("node-start").click();
  await page.getByTestId("edit-form").click();
  await page.getByTestId("form-builder-dialog").waitFor();
  await page.getByTestId("section-tab-2").click();
  await page.getByTestId("field-toggle-cost_total").click();
  await shot(page, "23-field-editor", true);

  await page.goto(`${BASE_URL}/admin/roles`);
  await shot(page, "24-roles");
  await page.getByTestId("open-role-Department Head").click();
  await page.getByTestId("role-detail").waitFor();
  await shot(page, "25-role-detail");
  await page.keyboard.press("Escape");

  await page.goto(`${BASE_URL}/admin/users`);
  await shot(page, "26-users");

  await page.goto(`${BASE_URL}/admin/departments`);
  await shot(page, "27-departments");

  await page.goto(`${BASE_URL}/admin/templates`);
  await shot(page, "28-email-templates");

  await page.goto(`${BASE_URL}/admin/audit`);
  await shot(page, "29-audit-log");

  await context.close();
}

async function mailbox(browser: Browser) {
  console.log("\nThe mail the run produced");
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: 1,
  });
  const page = await context.newPage();

  try {
    await page.goto(MAILPIT_URL, { timeout: 10_000 });
    await page.waitForTimeout(1500);
    await shot(page, "30-mailbox");
  } catch {
    console.log("  (no mail sink reachable - skipped)");
  }

  await context.close();
}

/* -------------------------------------------------------------------------- */
/*  The video                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Playwright writes one webm per context; the applicant's is the only one
 * recorded. ffmpeg speeds it up, trims it and builds a palette first, because
 * a GIF quantised on the fly looks like 1998.
 */
function buildGif() {
  const videos = fs.existsSync(VIDEO_DIR)
    ? fs.readdirSync(VIDEO_DIR).filter((name) => name.endsWith(".webm"))
    : [];

  if (videos.length === 0) {
    console.log("\nNo video recorded - skipping the GIF.");
    return;
  }

  const source = path.join(VIDEO_DIR, videos[0]);
  const palette = path.join(VIDEO_DIR, "palette.png");
  const gif = path.join(process.cwd(), "docs", "demo.gif");
  const filters = "setpts=PTS/3.2,fps=10,scale=900:-1:flags=lanczos";

  console.log("\nBuilding docs/demo.gif");
  execFileSync(
    "ffmpeg",
    [
      "-y",
      "-i",
      source,
      "-vf",
      `${filters},palettegen=stats_mode=diff`,
      palette,
    ],
    { stdio: "ignore" },
  );
  execFileSync(
    "ffmpeg",
    [
      "-y",
      "-i",
      source,
      "-i",
      palette,
      "-lavfi",
      `${filters}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3`,
      gif,
    ],
    { stdio: "ignore" },
  );

  fs.rmSync(VIDEO_DIR, { recursive: true, force: true });
  const size = (fs.statSync(gif).size / 1024 / 1024).toFixed(1);
  console.log(`  docs/demo.gif (${size} MB)`);
}

/* -------------------------------------------------------------------------- */

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  fs.rmSync(VIDEO_DIR, { recursive: true, force: true });

  const browser = await chromium.launch();

  console.log(`Photographing ${BASE_URL}`);
  const front = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: 1,
  });
  const page = await front.newPage();
  await page.goto(`${BASE_URL}/sign-in`);
  await shot(page, "01-sign-in");
  await front.close();

  await applicantJourney(browser);
  await departmentReview(browser);
  await assessment(browser);
  await departmentDecision(browser);
  await complianceCheck(browser);
  await finalApproval(browser);
  await reviewerHistory(browser);
  await administration(browser);
  await mailbox(browser);

  await browser.close();
  buildGif();

  console.log(`\nDone: ${shotCount} screenshots in docs/screenshots.`);
}

main().catch((error) => {
  console.error("\nScreenshot run failed:", error);
  process.exit(1);
});
